### ISSUE TITLE
Examples code(mnist.py) doesn't work

### ISSUE THREAD

**Issue by wakamezake** [oreilly-japan/deep-learning-from-scratch-3#1]
This Link is result of executing the examples_code(mnist.py).
[GoogleColabratory - deep-learning-from-scratch-3/try_mnist.py ](https://colab.research.google.com/drive/1mQ90NS4m4Ui0WqpPhl6J2rSsLb78UUGB)

### Enviroment info
```py
import dezero
dezero.__version__
# '0.0.11'

import sys
sys.version
# '3.6.8 (default, Oct  7 2019, 12:59:55) \n[GCC 8.3.0]'
```

### Execute Command
```
python examples/mnist.py
```

### Output
``` 
Downloading MNIST(train-images-idx3-ubyte.gz) ... Done
Downloading MNIST(train-labels-idx1-ubyte.gz) ... Done
Downloading MNIST(t10k-images-idx3-ubyte.gz) ... Done
Downloading MNIST(t10k-labels-idx1-ubyte.gz) ... Done
Traceback (most recent call last):
  File "examples/mnist.py", line 40, in <module>
    acc = F.accuracy(y, t)
  File "/usr/local/lib/python3.6/dist-packages/dezero-0.0.11-py3.6.egg/dezero/functions.py", line 367, in accuracy
    return Variable(acc)
  File "/usr/local/lib/python3.6/dist-packages/dezero-0.0.11-py3.6.egg/dezero/core.py", line 49, in __init__
    raise TypeError('{} is not supported'.format(type(data)))
TypeError: <class 'numpy.float64'> is not supported
```

**Comment by koki0702** [comment]
Thanks!
I just fixed the problem.
7ce3f51e0addc24ed606c97e38f0e6e56e8b2f4c
